/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nenad' at '1/15/18 7:44 AM' with Gradle 2.8
 *
 * @author nenad, @date 1/15/18 7:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
